name: shell-commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github Action"
      - name: Multiline script
        run: |
          node -v
          npm -v
